---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---

# A música en Grecia e Roma

\minitoc <!-- índice do tema-->

## Obxectivos do tema

* Comprender que a música é parte da historia do home.
* Coñecer o contexto histórico-cultural e o significado da música na sociedade grecorromana.
* Saber comentar as características dos instrumentos e da música desta época, a través da audición ou da partitura.
* Entender os conceptos derivados da teoría musical.
* Entender a importancia das fontes literarias e iconográficas para poder extraer conclusións respecto ao papel da música na antiga Grecia e Roma.

## A música na sociedade e culturas grega

<!--### As fontes de información-->

### A música como ideal educativo

### O sistema musical

#### Notas, intervalos, xéneros e sistemas de escalas

#### Notación musical

### O pensamento musical

#### A escola pitagórica

#### O pensamento platónico e aristotélico

### A música instrumental

### Organoloxía. Cítara e aulos

## Actividades e audicións

## Resumo do tema


